### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [10]:
# numpy.zeros
import numpy as np
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# numpy.ones
ones_array = np.ones((2, 3))
print(ones_array)
ones_3d_array = np.ones((3, 4, 2))
print("\n",ones_3d_array)

[[1. 1. 1.]
 [1. 1. 1.]]

 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [12]:
# numpy.full
full_array = np.full((2, 3), 5)
print(full_array)
full_3d_array = np.full((3, 4, 2), 3.14)
print("\n")
print(full_3d_array)


[[5 5 5]
 [5 5 5]]


[[[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]]


In [13]:
# numpy.eye
eye_matrix_3x3 = np.eye(3)
print(eye_matrix_3x3)
eye_matrix_offset = np.eye(5, k=1)
print("\n")
print(eye_matrix_offset)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [14]:
# numpy.arange
arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(1, 11, 2)
print("\n")
print(arr2)
arr3 = np.arange(3, 0, -1)
print("\n")
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


[1 3 5 7 9]


[3 2 1]


In [17]:
# numpy.add
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

result = np.add(arr1, arr2)

print(result)

[ 6  8 10 12]


In [18]:
# numpy.subtract
arr1 = np.array([5, 10, 15, 20])
arr2 = np.array([2, 3, 4, 5])

result = np.subtract(arr1, arr2)
print(result)

[ 3  7 11 15]


In [19]:
# numpy.sin
arr = np.arange(0, np.pi, 0.5)
print(arr)

sin_arr = np.sin(arr)
print(sin_arr)

[0.  0.5 1.  1.5 2.  2.5 3. ]
[0.         0.47942554 0.84147098 0.99749499 0.90929743 0.59847214
 0.14112001]


In [21]:
# numpy.multiply
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

result = np.multiply(arr1, arr2)
print(result)

[ 5 12 21 32]


In [22]:
# numpy.sqrt
arr = np.array([4, 9, 16, 25])

sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[2. 3. 4. 5.]


In [23]:
# numpy.dot
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Умножение матриц
result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[19 22]
 [43 50]]


In [24]:
# numpy.sum
arr = np.array([[1, 2], [3, 4]])

total_sum = np.sum(arr)
print(total_sum)

10


In [25]:
# numpy.zeros_like
arr = np.array([[1, 2], [3, 4]])

zeros_like_arr = np.zeros_like(arr)
print(zeros_like_arr)

[[0 0]
 [0 0]]


In [27]:
# numpy.empty_like
arr = np.array([[1, 2], [3, 4]])
empty_like_arr = np.empty_like(arr)
print(empty_like_arr)

[[1 2]
 [3 4]]


In [ ]:
# numpy.reshape


In [ ]:
# numpy.isnan


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [29]:
# numpy.random.sample
arr = np.arange(1, 10)
print(arr)

reshaped_arr = np.reshape(arr, (3, 3))
print("\n")
print(reshaped_arr)

[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# numpy.random.random
random_array = np.random.random((2, 3))
print(random_array)

[[0.6401527  0.83281946 0.17386933]
 [0.11140112 0.77652459 0.17612255]]


In [34]:
# numpy.random.randint
random_integers = np.random.randint(0, 10, size=(2, 3))
print(random_integers)

[[9 6 4]
 [0 3 9]]


In [37]:
# numpy.random.random_integers
random_integers = np.random.randint(1, 11, size=(2, 3))
print(random_integers)

[[9 4 6]
 [4 7 4]]


In [38]:
# numpy.random.uniform
random_uniform = np.random.uniform(0.0, 1.0, size=(2, 3))
print(random_uniform)

[[0.90134    0.42931915 0.67644239]
 [0.94186891 0.67426623 0.78818205]]


In [39]:
# numpy.random.seed
np.random.seed(42)
random_integers = np.random.randint(0, 10, size=(2, 3))
print(random_integers)

[[6 3 7]
 [4 6 9]]


In [40]:
# numpy.random.shuffle
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [41]:
# numpy.random.permutation
arr = np.array([1, 2, 3, 4, 5])
permuted_arr = np.random.permutation(arr)
print(permuted_arr)

[4 2 1 5 3]


In [42]:
# numpy.random.choice
arr = np.array([1, 2, 3, 4, 5])
random_elements = np.random.choice(arr, size=3, replace=False)
print(random_elements)

[5 4 1]


# Прекрасная работа!