### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.21.5


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [2]:
# Начало вашего кода
even_numbers = np.arange(0, 10, 2)
odd_numbers = np.arange(1, 10, 2) 
numbers = np.vstack([even_numbers, odd_numbers])
# Конец вашего кода
print(numbers)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [17]:
# Начало вашего кода
numbers = numbers.T
print(numbers.ndim)  
print(numbers.shape) 
print(numbers.size)  
print(numbers.dtype)  
print(numbers)
# Конец вашего кода

2
(2, 5)
10
int32
[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [18]:
# Начало вашего кода
overall_max = np.max(numbers)  
overall_min = np.min(numbers) 
overall_mean = np.mean(numbers) 
overall_std = np.std(numbers)
# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [19]:
# Начало вашего кода
col_max = np.max(numbers, axis=0)  
col_min = np.min(numbers, axis=0)
col_mean = np.mean(numbers, axis=0)  
col_std = np.std(numbers, axis=0)  

# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[1 3 5 7 9]
[0 2 4 6 8]
[0.5 2.5 4.5 6.5 8.5]
[0.5 0.5 0.5 0.5 0.5]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [20]:
# Начало вашего кода
row_max = np.max(numbers, axis=1, keepdims=True)  
row_min = np.min(numbers, axis=1, keepdims=True)  
row_mean = np.mean(numbers, axis=1, keepdims=True)  
row_std = np.std(numbers, axis=1, keepdims=True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [21]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [24]:
mean_axis_0 = np.mean(thd_nparr, axis=0)
std_axis_0 = np.std(thd_nparr, axis=0)

mean_axis_1 = np.mean(thd_nparr, axis=1)
std_axis_1 = np.std(thd_nparr, axis=1)

mean_axis_2 = np.mean(thd_nparr, axis=2)
std_axis_2 = np.std(thd_nparr, axis=2)

print("Mean with respect to 0-axis")
print(mean_axis_0)
print("STD with respect to 0-axis")
print(std_axis_0)

print("\nMean with respect to 1-axis")
print(mean_axis_1)
print("STD with respect to 1-axis")
print(std_axis_1)

print("\nMean with respect to 2-axis")
print(mean_axis_2)
print("STD with respect to 2-axis")
print(std_axis_2)

Mean with respect to 0-axis
[[11. 12.]
 [13. 14.]]
STD with respect to 0-axis
[[10. 10.]
 [10. 10.]]

Mean with respect to 1-axis
[[ 2.  3.]
 [22. 23.]]
STD with respect to 1-axis
[[1. 1.]
 [1. 1.]]

Mean with respect to 2-axis
[[ 1.5  3.5]
 [21.5 23.5]]
STD with respect to 2-axis
[[0.5 0.5]
 [0.5 0.5]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [26]:
# ndarray.reshape()
# Начало вашего кода
arr = np.arange(12)
print("Stock")
print(arr)

reshaped_arr = arr.reshape(3, 4)
print("\nReshaped:")
print(reshaped_arr)
# Конец вашего кода

Stock
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
# ndarray.ravel()
# Начало вашего кода
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("stock:")
print(arr)

# Преобразование в одномерный массив
raveled_arr = arr.ravel()
print("\nWith ravel():")
print(raveled_arr)
# Конец вашего кода

stock:
[[1 2 3]
 [4 5 6]]

With ravel():
[1 2 3 4 5 6]


In [41]:
# ndarray.tolist()
# Начало вашего кода

arr_list = arr.tolist()
print("\nWith tolist():")
print(arr_list)
# Конец вашего кода


With tolist():
[3, 1, 6, 5, 4]


In [42]:
# ndarray.tofile()
# Начало вашего кода

file_path = 'array_data.bin'
arr.tofile(file_path)
# Конец вашего кода

In [47]:
# ndarray.sort()
# Начало вашего кода
arr = np.array([3, 1, 2, 5, 4])
arr.sort()
print("Отсортированный массив:")
print(arr)
# Конец вашего кода

Отсортированный массив:
[1 2 3 4 5]


In [48]:
# ndarray.transpose()
# Начало вашего кода
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Исходный массив:")
print(arr)

transposed_arr = arr.transpose()
print("\nТранспонированный массив:")
print(transposed_arr)
# Конец вашего кода

Исходный массив:
[[1 2]
 [3 4]
 [5 6]]

Транспонированный массив:
[[1 3 5]
 [2 4 6]]


In [49]:
# ndarray.flatten()
# Начало вашего кода
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("array:")
print(arr)

# Преобразование в одномерный массив
flattened_arr = arr.flatten()
print("\nafter flatten():")
print(flattened_arr)
# Конец вашего кода

array:
[[1 2 3]
 [4 5 6]]

after flatten():
[1 2 3 4 5 6]


In [52]:
# ndarray.argmin()
arr = np.array([3, 1, 6, 5, 4])
index_of_min = arr.argmin()
print(index_of_min)
# Конец вашего кода

1


In [38]:
# ndarray.argmax()
# Начало вашего кода
index_of_max = arr.argmax()
print(index_of_max)
# Конец вашего кода

2


In [55]:
# ndarray.cumsum()
# Начало вашего кода
cumulative_sum = arr.cumsum()
print( cumulative_sum)
# Конец вашего кода

[ 3  4 10 15 19]


In [56]:
# ndarray.cumprod()
# Начало вашего кода
cumulative_product = arr.cumprod()
print(cumulative_product)
# Конец вашего кода

[  3   3  18  90 360]


In [58]:
# ndarray.dot()
# Начало вашего кода
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Выполнение умножения матриц
result = a.dot(b)
print(result)
# Конец вашего кода

[[19 22]
 [43 50]]


In [59]:
# ndarray.squeeze()
# Начало вашего кода
arr = np.array([[[1], [2], [3]]])
squeezed_arr = arr.squeeze()
print(squeezed_arr)
# Конец вашего кода

[1 2 3]


In [60]:
# ndarray.repeat()
# Начало вашего кода
arr = np.array([1, 2, 3])
repeated_arr = arr.repeat(3)
print(repeated_arr)
# Конец вашего кода

[1 1 1 2 2 2 3 3 3]


# Прекрасная работа!