### NumPy: Введение (Часть 1) [Домашнее задание]

### Задания:

1. Установите пакет NumPy с помощью pip.

2. Пожалуйста, импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.21.5


### Ожидаемый результат
```
1.17.4
```

3. Создайте одномерный numpy.ndarray even_np, в котором он содержит четные числа только от 0 до 10.

In [2]:
# Начало вашего кода
even_np = np.arange(0, 11, 2)
# Конец вашего кода
print(even_np)

[ 0  2  4  6  8 10]


### Ожидаемый результат
```
[ 0  2  4  6  8 10]
```

4. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [3]:
# Начало вашего кода
even_np = np.arange(0, 11, 2)
print(even_np.ndim)  
print(even_np.shape) 
print(even_np.size)
print(even_np.dtype)  
print(even_np) 
# Конец вашего кода

1
(6,)
6
int32
[ 0  2  4  6  8 10]


### Ожидаемый результат
```
1
(6,)
6
int64
[ 0  2  4  6  8 10]
```

5. Создайте одномерный numpy.ndarray odd_np, в котором он содержит не четные числа только от 10 до 20, и тип элементов должен быть **комплексными числами.**

In [4]:
# Начало вашего кода
odd_np = np.arange(11, 20, 2, dtype=np.complex)
# Конец вашего кода
print(odd_np)

[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


C:\Users\iskan\AppData\Local\Temp\ipykernel_13108\677955500.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  odd_np = np.arange(11, 20, 2, dtype=np.complex)


### Ожидаемый результат
```
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

6. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray odd_np и распечатайте их.

In [6]:
# Начало вашего кода
odd_np = np.arange(11, 20, 2, dtype=np.complex)
print(odd_np.ndim)  
print(odd_np.shape) 
print(odd_np.size) 
print(odd_np.dtype)  
print(odd_np)
# Конец вашего кода

1
(5,)
5
complex128
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


C:\Users\iskan\AppData\Local\Temp\ipykernel_13108\1370006576.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  odd_np = np.arange(11, 20, 2, dtype=np.complex)


### Ожидаемый результат
```
1
(5,)
5
complex128
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

# Прекрасная работа!