# Пожалуйста, выполните задачи ниже.

Вам может понадобиться больше узнать о методах, предоставляемых пакетом Numpy.

1. Создайте числовые массивы формы ```(20,5)``` со случайно сгенерированными целыми числами от 1 до 1000 (```numpy.random```). Установите ```seed=1```.

In [1]:
# Начало вашего кода
import numpy as np

np.random.seed(1)
array = np.random.randint(1, 1001, size=(20, 5))
print(array)
# Конец вашего кода


[[  38  236  909   73  768]
 [ 906  716  646  848  961]
 [ 145  130  973  584  750]
 [ 509  391  282  179  277]
 [ 255  358  915  469  908]
 [ 253  491  669  926  399]
 [ 563  581  216  984  754]
 [ 504  479  865   87  142]
 [ 394    8  320  830  535]
 [ 314  514  897  317  210]
 [ 265  729  654  628  432]
 [ 634  457  543   72  388]
 [ 455  918  562  314  516]
 [ 965  793  498   44  589]
 [  27  821  337  622  884]
 [ 298  467   16   65  197]
 [  26  368  739  472  904]
 [ 283  666  617   23  778]
 [ 708 1000  127  280  382]
 [ 357  156  934  314  596]]


### Ожидаемый результат:

```
[[ 38 236 909  73 768]
 [906 716 646 848 961]
 [145 130 973 584 750]
 [509 391 282 179 277]
 [255 358 915 469 908]
 [253 491 669 926 399]
 [563 581 216 984 754]
 [504 479 865  87 142]
 [394   8 320 830 535]
 [314 514 897 317 210]
 [265 729 654 628 432]
 [634 457 543  72 388]
 [455 918 562 314 516]
 [965 793 498  44 589]
 [ 27 821 337 622 884]
 [298 467  16  65 197]
 [ 26 368 739 472 904]
 [283 666 617  23 778]
 [708 127 280 382 357]
 [156 934 314 596 167]]
```

2. Каково среднее значение третьего столбца?

In [3]:
# Начало вашего кода
third_column_mean = np.mean(array[:, 2])
print(third_column_mean)
# Конец вашего кода

585.95


### Ожидаемый результат:

```
562.6
```

3. Каково среднее значение последних 5 строк второго и третьего столбцов?

In [6]:
# Начало вашего кода
last_five_rows_mean = np.mean(array[-5:, 1:3])
print(last_five_rows_mean)
# Конец вашего кода

509.0


### Ожидаемый результат:

```
350.4
```

4. Выберите числа из последнего столбца массива, которые больше 30 и меньше, чем 500.

In [7]:
# Начало вашего кода
filtered_numbers = array[(array[:, -1] > 30) & (array[:, -1] < 500), -1]
print(filtered_numbers)
# Конец вашего кода

[277 399 142 210 432 388 197 382]


### Ожидаемый результат:

```
[399 432 388 357]
```

5. Напишите функцию, которая проверяет, равен ли какой-либо из элементов данного массива numpy нулю.

In [10]:
def check_zeros(input_arr):
    # Начало вашего кода
    return np.any(input_arr == 0)
    # Конец вашего кода
print(check_zeros(array))

False


### Ожидаемый результат:

```
False
```

6. Пожалуйста, сгенерируйте массив из пяти случайных чисел из равномерного распределения.

In [11]:
# Начало вашего кода
arr_norm = np.random.rand(5)
# Конец вашего кода
print(arr_norm)

[0.91686133 0.91044838 0.29893011 0.58438912 0.56591203]


### Ожидаемый результат:

```
[0.21162812 0.26554666 0.49157316 0.05336255 0.57411761]
```

7. Пожалуйста, сгенерируйте массив случайных чисел формы 3х3х4 из равномерного распределения.

In [12]:
# Начало вашего кода
arr3d = np.random.rand(3, 3, 4)
# Конец вашего кода
print(arr3d)

[[[0.61393832 0.95653566 0.26097898 0.23101542]
  [0.53344849 0.94993814 0.49305959 0.54060051]
  [0.7654851  0.04534573 0.13996612 0.79240359]]

 [[0.02980136 0.88312548 0.54078819 0.44798018]
  [0.89213587 0.37758434 0.53842469 0.65229888]
  [0.36126102 0.57100856 0.63783648 0.12631489]]

 [[0.69020459 0.6477494  0.35393909 0.76323305]
  [0.35653172 0.75278835 0.88134183 0.01166919]
  [0.49810907 0.07379201 0.78695147 0.06406733]]]


### Ожидаемый результат:

```
[[[0.14672857 0.58930554 0.69975836 0.10233443]
  [0.41405599 0.69440016 0.41417927 0.04995346]
  [0.53589641 0.66379465 0.51488911 0.94459476]]

 [[0.58655504 0.90340192 0.1374747  0.13927635]
  [0.80739129 0.39767684 0.1653542  0.92750858]
  [0.34776586 0.7508121  0.72599799 0.88330609]]

 [[0.62367221 0.75094243 0.34889834 0.26992789]
  [0.89588622 0.42809119 0.96484005 0.6634415 ]
  [0.62169572 0.11474597 0.94948926 0.44991213]]]
```

8. Пожалуйста, сгенерируйте массив случайных чисел формы 5х5 из равномерного распределения и найдите минимальное и максимальное значения.

In [13]:
# Начало вашего кода
arr2d = np.random.rand(5, 5)
min_val = np.min(arr2d)
max_val = np.max(arr2d)
# Конец вашего кода
print(arr2d)
print(min_val)
print(max_val)

[[0.35531036 0.94183695 0.37980329 0.76292007 0.771595  ]
 [0.3013605  0.77273915 0.15292982 0.57863393 0.009008  ]
 [0.70904252 0.47064081 0.76459257 0.46739268 0.26900105]
 [0.83169259 0.55132494 0.0700815  0.47247504 0.74276483]
 [0.19195608 0.4643115  0.23036281 0.50824754 0.20856831]]
0.00900799696104293
0.9418369487534225


### Ожидаемый результат:

```
[[0.57838961 0.4081368  0.23702698 0.90337952 0.57367949]
 [0.00287033 0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124 0.92943723]
 [0.69089692 0.99732285 0.17234051 0.13713575 0.93259546]
 [0.69681816 0.06600017 0.75546305 0.75387619 0.92302454]]
0.00287032703115897
0.9973228504514805
```

9. Пожалуйста, перетасуйте (```np.random```) цифры от 0 до 10 (включительно) 

In [16]:
# Начало вашего кода
arr_shuf = np.arange(11)  
np.random.shuffle(arr_shuf)
# Конец вашего кода
print(arr_shuf)

[ 7 10  8  9  1  6  3  5  0  2  4]


### Ожидаемый результат:

```
[10  3  6  1  0  4  8  5  7  2  9]
```

10. Пожалуйста, создайте массив (10,) случайных чисел и отсортируйте его

In [17]:
# Начало вашего кода
arr = np.random.rand(10)
arr_sort = np.sort(arr)
# Конец вашего кода
print(arr_sort)

[0.04455188 0.05991769 0.10749413 0.12134346 0.13645523 0.22570934
 0.55624023 0.71298898 0.74712164 0.86354185]


### Ожидаемый результат:

```
[0.09155644 0.10213523 0.23175846 0.23362252 0.27831884 0.28871783
 0.36784324 0.41792654 0.57006666 0.96766793]
```

### Пожалуйста, найдите все ошибки в коде и исправьте.

Помните, что блок кодов может содержать более 1 ошибки.

11. Ожидаемый результат:

```
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]
```

In [18]:
print(np.linspace(0, 20, 20))

[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


12. Ожидаемый результат:

```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
```

In [ ]:
print(np.arange(100))

13. Ожидаемый результат:

```
[[[[0.14672857 0.58930554 0.69975836]
   [0.10233443 0.41405599 0.69440016]]

  [[0.41417927 0.04995346 0.53589641]
   [0.66379465 0.51488911 0.94459476]]

  [[0.58655504 0.90340192 0.1374747 ]
   [0.13927635 0.80739129 0.39767684]]]


 [[[0.1653542  0.92750858 0.34776586]
   [0.7508121  0.72599799 0.88330609]]

  [[0.62367221 0.75094243 0.34889834]
   [0.26992789 0.89588622 0.42809119]]

  [[0.96484005 0.6634415  0.62169572]
   [0.11474597 0.94948926 0.44991213]]]]
```

In [22]:
print(np.reshape(arr3d, (3, 2, 3, -1)))

[[[[0.2603151  0.80475456]
   [0.19343428 0.63946088]
   [0.52467031 0.92480797]]

  [[0.26329677 0.06596109]
   [0.73506596 0.77217803]
   [0.90781585 0.93197207]]]


 [[[0.01395157 0.23436209]
   [0.61677836 0.94901632]
   [0.95017612 0.55665319]]

  [[0.91560635 0.64156621]
   [0.39000771 0.48599067]
   [0.60431048 0.54954792]]]


 [[[0.92618143 0.91873344]
   [0.39487561 0.96326253]
   [0.17395567 0.12632952]]

  [[0.13507916 0.50566217]
   [0.02152481 0.94797021]
   [0.82711547 0.01501898]]]]


14. Ожидаемый результат:

``` 
[32. 19. 25. 21. 26. 18. 22. 27. 37. 14.]

```

In [24]:
np.random.seed(2)
arr1 = np.ones(5) * 8
arr2 = np.random.randint(0, high=10, size=(10, 5))
result = np.sum(arr1 * arr2, axis=1)
print(result)

[256. 152. 200. 168. 208. 144. 176. 216. 296. 112.]


15. Ожидаемый результат:

``` 
[[2.32624478 2.99713989 2.11483556 2.3372708  4.24467882]]

```

In [25]:
result = arr1.dot(arr2d)
print(result)

[19.11489638 25.60682678 12.78215987 22.3173541  16.0074975 ]


# Прекрасная работа!